language: clojure
lein: 2.9.1
sudo: false

dist: trusty

install:
  # Get recent node:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g eclint

before_script:
  - eclint check .* **
  - |
    (cd cloverage && \
        lein do cljfmt check, \
                eastwood , \
                kibit)
  - (cd lein-cloverage && lein do cljfmt check, eastwood, kibit)

script:
  - (cd cloverage && lein test)
  - (cd lein-cloverage && lein test)

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk9
  - openjdk11

after_success:
  - bash deploy.sh
