version: 2.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.9.1
    steps:
      - run:
          name: Remove often erroneous Git config
          command: rm -rf /home/circleci/.gitconfig
      - checkout

      ################################################################################
      # setup dependencies

      - restore_cache:
          keys:
            - v1-jars-{{ checksum "cloverage/project.clj" }}-{{ checksum "lein-cloverage/project.clj" }}
            - v1-jars-
      - run:
          name: (cloverage) install dependencies
          command: lein deps
          working_directory: ./cloverage
      - run:
          name: (lein-cloverage) install dependencies
          command: lein deps
          working_directory: ./lein-cloverage
      - save_cache:
          key: v1-jars-{{ checksum "cloverage/project.clj" }}-{{ checksum "lein-cloverage/project.clj" }}
          paths:
            - ~/.m2

      ################################################################################
      # cloverage tests

      - run:
          name: (cloverage) tests
          command: lein test
          working_directory: ./cloverage
      - run:
          name: (cloverage) cljfmt
          command: lein cljfmt check
          working_directory: ./cloverage
      - run:
          name: (cloverage) eastwood
          command: lein eastwood
          working_directory: ./cloverage
      - run:
          name: (cloverage) kibit
          command: lein kibit
          working_directory: ./cloverage

      ################################################################################
      # lein-cloverage tests

      - run:
          name: (lein-cloverage) tests
          command: lein test
          working_directory: ./lein-cloverage
      - run:
          name: (lein-cloverage) cljfmt
          command: lein cljfmt check
          working_directory: ./lein-cloverage
      - run:
          name: (lein-cloverage) eastwood
          command: lein eastwood
          working_directory: ./lein-cloverage
      - run:
          name: (lein-cloverage) kibit
          command: lein kibit
          working_directory: ./lein-cloverage
